# Nama : Dimas Arya Nugraha

# Nim : 2109106019

# Kelas : Informatika A'21

# Posttest 7 : Tensorflow

#

# Import Library

In [38]:
import tensorflow as tf
import numpy as np

#

# 1. Membuat sebuah tensor dengan shape (5,5) dengan nilai random yang disimpan dalam variabel random_tensor

In [39]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1., seed=1)
random_tensor.numpy()

array([[-0.09829053,  1.2328393 ,  1.0841055 , -0.03147423,  0.8239386 ],
       [-1.343977  , -0.5825029 , -1.2442445 ,  0.78904885, -1.5128906 ],
       [ 2.1204236 ,  0.8943947 , -0.08512403, -3.0256145 ,  0.0541295 ],
       [ 0.4327671 , -0.29732513,  0.9791035 ,  1.6596949 ,  0.11454969],
       [ 0.01530319, -0.2602644 , -0.7217767 , -0.8932251 ,  0.35070774]],
      dtype=float32)

In [40]:
list_utt = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]

utt = tf.convert_to_tensor(list_utt)
utt.numpy()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
slicing = tf.random.normal([5,5,5])
slicing.numpy()

array([[[ 0.9409927 , -1.5170689 ,  0.18557556,  1.2530341 ,
          1.9363809 ],
        [-0.7988196 , -0.7972447 , -0.28352404, -0.80268157,
          0.7863386 ],
        [-0.40598786, -0.7324708 ,  0.14650163,  0.4634121 ,
         -0.0721753 ],
        [ 0.09316005,  0.6003364 , -0.7321259 , -0.94157374,
          1.2275326 ],
        [ 0.04960457,  0.5253416 , -2.3639956 ,  0.27520692,
          1.8701777 ]],

       [[-1.0425793 , -0.02102177, -0.20001023, -1.3953463 ,
          0.8258715 ],
        [-0.17418545, -1.2276788 , -0.5240789 , -1.5253825 ,
          0.9314845 ],
        [-0.57686144, -1.3870463 ,  0.41863173,  0.34450477,
          0.7608774 ],
        [ 0.8999918 ,  1.3924136 , -2.1533494 ,  0.30152616,
          0.8976059 ],
        [ 0.8920964 , -1.1558073 , -0.42994562,  0.58900464,
         -0.19109857]],

       [[ 0.9623473 , -0.609431  ,  0.50142   , -0.0145657 ,
         -1.0211928 ],
        [ 2.384155  , -1.0210652 ,  1.4938141 ,  0.93606496,
          0

In [42]:
tf.gather(slicing, indices=[2,2,2]).numpy()

array([[[ 0.9623473 , -0.609431  ,  0.50142   , -0.0145657 ,
         -1.0211928 ],
        [ 2.384155  , -1.0210652 ,  1.4938141 ,  0.93606496,
          0.46287864],
        [-0.14572863,  0.3671695 , -1.3526266 ,  0.19628999,
          1.5746385 ],
        [-0.8652125 , -0.26479527,  1.3862567 ,  1.2539145 ,
          0.27839005],
        [-1.4489396 ,  0.51224667, -0.29424906, -0.4277893 ,
         -0.6452919 ]],

       [[ 0.9623473 , -0.609431  ,  0.50142   , -0.0145657 ,
         -1.0211928 ],
        [ 2.384155  , -1.0210652 ,  1.4938141 ,  0.93606496,
          0.46287864],
        [-0.14572863,  0.3671695 , -1.3526266 ,  0.19628999,
          1.5746385 ],
        [-0.8652125 , -0.26479527,  1.3862567 ,  1.2539145 ,
          0.27839005],
        [-1.4489396 ,  0.51224667, -0.29424906, -0.4277893 ,
         -0.6452919 ]],

       [[ 0.9623473 , -0.609431  ,  0.50142   , -0.0145657 ,
         -1.0211928 ],
        [ 2.384155  , -1.0210652 ,  1.4938141 ,  0.93606496,
          0

In [43]:
tf.gather_nd(slicing, indices=[[0,2],[1,2],[2,2],[3,2],[4,2]]).numpy()

array([[-0.40598786, -0.7324708 ,  0.14650163,  0.4634121 , -0.0721753 ],
       [-0.57686144, -1.3870463 ,  0.41863173,  0.34450477,  0.7608774 ],
       [-0.14572863,  0.3671695 , -1.3526266 ,  0.19628999,  1.5746385 ],
       [ 0.01916992, -0.18794642, -0.46912897,  0.61926097, -0.450291  ],
       [-0.7102787 ,  0.7113245 ,  0.7207577 ,  0.25339675, -0.9933147 ]],
      dtype=float32)

In [44]:
tf.gather_nd(slicing, indices=[[0,2,2],[1,2,2],[2,2,2],[3,2,2],[4,2,2]]).numpy()

array([ 0.14650163,  0.41863173, -1.3526266 , -0.46912897,  0.7207577 ],
      dtype=float32)

# 

# 2. Membuat tensor dengan shape(5,5) dari list dengan nilai bilangan prima dalam variabel prime_tensor

In [45]:
list_prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 101]]
prime_tensor = tf.constant(list_prime, dtype=tf.float32)
prime_tensor.numpy()

array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)

#

# 3.Menampilkan dimensi dari kedua variabel (random dan prime tensor)

In [46]:
random_tensor.shape

TensorShape([5, 5])

In [47]:
prime_tensor.shape

TensorShape([5, 5])

#

# 4. Menampilkan Hasil perhitungan aritmatika menggunakan 2 variabel tadi (Random dan Prime) minimal 5 operator

In [48]:
print("1. Penjumlahan :",tf.add(prime_tensor,random_tensor))
print("\n2. Pengurangan :",tf.subtract(prime_tensor,random_tensor))
print("\n3. Perkalian :",tf.multiply(prime_tensor,random_tensor))
print("\n4. Pembagian :",tf.divide(prime_tensor,random_tensor))
print("\n5. Pangkat :",tf.pow(prime_tensor,random_tensor))
print("\n6. Setara :",tf.equal(prime_tensor,random_tensor))
print("\n7. Tidak Setara :",tf.not_equal(prime_tensor,random_tensor))
print("\n8. Less :",tf.math.less(prime_tensor,random_tensor))
print("\n9. Maximum :",tf.math.maximum(prime_tensor,random_tensor))
print("\n10. Minimum :",tf.math.minimum(prime_tensor,random_tensor))

1. Penjumlahan : tf.Tensor(
[[  1.9017094   4.2328396   6.0841055   6.968526   11.823938 ]
 [ 11.656023   16.417498   17.755756   23.78905    27.48711  ]
 [ 33.120422   37.894394   40.914875   39.974384   47.05413  ]
 [ 53.432766   58.702675   61.979103   72.6597     73.11455  ]
 [ 79.015305   82.73974    88.27822    96.10677   101.35071  ]], shape=(5, 5), dtype=float32)

2. Pengurangan : tf.Tensor(
[[  2.0982904   1.7671607   3.9158945   7.031474   10.176062 ]
 [ 14.343977   17.582502   20.244244   22.21095    30.51289  ]
 [ 28.879576   36.105606   41.085125   46.025616   46.94587  ]
 [ 52.567234   59.297325   60.020897   69.3403     72.88545  ]
 [ 78.984695   83.26026    89.72178    97.89323   100.64929  ]], shape=(5, 5), dtype=float32)

3. Perkalian : tf.Tensor(
[[  -0.19658105    3.698518      5.4205275    -0.2203196     9.063325  ]
 [ -17.4717       -9.90255     -23.640644     18.148123    -43.873825  ]
 [  65.73313      33.092606     -3.4900854  -130.10143       2.5440862 ]
 [  2

#

# 5. Tampilkan Nilai Maksimal dan Minimal dari variabel random_tensor

### Maximal

In [49]:
# Max Baris
tf.argmax(random_tensor, axis=0).numpy()


array([2, 0, 0, 3, 0], dtype=int64)

In [50]:
# Max Kolom
tf.argmax(random_tensor, axis=1).numpy()

array([1, 3, 0, 3, 4], dtype=int64)

### Minimal

In [51]:
# Min baris
tf.argmin(random_tensor, axis=0).numpy()

array([1, 1, 1, 2, 1], dtype=int64)

In [52]:
# Min kolom
tf.argmin(random_tensor, axis=1).numpy()

array([0, 4, 3, 1, 3], dtype=int64)

#

# 6. Menampilkan hasil penggabungan variabel Random_tensor dengan Prime_tensor (concatenation)

## Penggabungan baris

In [53]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()

array([[-9.8290525e-02,  1.2328393e+00,  1.0841055e+00, -3.1474229e-02,
         8.2393861e-01],
       [-1.3439770e+00, -5.8250290e-01, -1.2442445e+00,  7.8904885e-01,
        -1.5128906e+00],
       [ 2.1204236e+00,  8.9439470e-01, -8.5124031e-02, -3.0256145e+00,
         5.4129496e-02],
       [ 4.3276709e-01, -2.9732513e-01,  9.7910351e-01,  1.6596949e+00,
         1.1454969e-01],
       [ 1.5303185e-02, -2.6026440e-01, -7.2177672e-01, -8.9322507e-01,
         3.5070774e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
         1.0100000e+02]], dtype=float32)

##

## Penggabungan Kolom

In [54]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy()

array([[-9.8290525e-02,  1.2328393e+00,  1.0841055e+00, -3.1474229e-02,
         8.2393861e-01,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [-1.3439770e+00, -5.8250290e-01, -1.2442445e+00,  7.8904885e-01,
        -1.5128906e+00,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 2.1204236e+00,  8.9439470e-01, -8.5124031e-02, -3.0256145e+00,
         5.4129496e-02,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [ 4.3276709e-01, -2.9732513e-01,  9.7910351e-01,  1.6596949e+00,
         1.1454969e-01,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [ 1.5303185e-02, -2.6026440e-01, -7.2177672e-01, -8.9322507e-01,
         3.5070774e-01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0100000e+02]], dtype=float32)

#

# Menampilkan hasil sorting dari kedua variabel (random_tensor dan prime_tensor) secara menurun/Ascending

## Sort Random_Tensor (Descending)

In [55]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[ 1.2328393 ,  1.0841055 ,  0.8239386 , -0.03147423, -0.09829053],
       [ 0.78904885, -0.5825029 , -1.2442445 , -1.343977  , -1.5128906 ],
       [ 2.1204236 ,  0.8943947 ,  0.0541295 , -0.08512403, -3.0256145 ],
       [ 1.6596949 ,  0.9791035 ,  0.4327671 ,  0.11454969, -0.29732513],
       [ 0.35070774,  0.01530319, -0.2602644 , -0.7217767 , -0.8932251 ]],
      dtype=float32)

In [56]:
sort_random_tensor2 = tf.argsort(random_tensor, direction="DESCENDING")
sort_random_tensor2.numpy()

array([[1, 2, 4, 3, 0],
       [3, 1, 2, 0, 4],
       [0, 1, 4, 2, 3],
       [3, 2, 0, 4, 1],
       [4, 0, 1, 2, 3]])

###

## Sort Prime_Tensor (Descending)

In [57]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[ 11.,   7.,   5.,   3.,   2.],
       [ 29.,  23.,  19.,  17.,  13.],
       [ 47.,  43.,  41.,  37.,  31.],
       [ 73.,  71.,  61.,  59.,  53.],
       [101.,  97.,  89.,  83.,  79.]], dtype=float32)

In [58]:
sort_prime_tensor2 = tf.argsort(prime_tensor, direction="DESCENDING")
sort_prime_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])